### PR TITLE
ported the example to typescript

### PR DESCRIPTION
**Pull request by Haringat**
Should help with #80.

### CODE REVIEW

**Comment by jlord** [comment]
Thanks for taking the time to work on this @Haringat! In #80 I mentioned creating a fork because I don't think this one repository should contain _multiple_ options, but rather be the simplest version possible. Many people starting with Electron may not need the extra files or know what they're for. 

If you wanted to create that fork I'd be happy to link to it from the `README` here instead of the proposed changes in this Pull Request. Thanks!

**Comment by zeke** [comment]
> happy to link to it from the README here instead

👍

**Comment by Haringat** [comment]
Why don't you just add a "typescript" branch to the repository?

**Comment by zeke** [comment]
We could do that, but like @jlord said, the object of this repo is to demonstrate the simplest possible Electron app with a minimum of external dependencies.

If you want more people to see your TypeScript fork, I would suggest adding your repo to the list of boilerplates on https://github.com/sindresorhus/awesome-electron -- that way it will show up on that repo and eventually [the Electron website](http://electron.atom.io/community/#boilerplates) as well.

**Pull request closed without merging**
