### PR TITLE
chore: update .gitignore

### PR DESCRIPTION
**Pull request by shauryaaher**
node_modules is a folder, not a file.

### CODE REVIEW

**Comment by shauryaaher** [comment]
Please can you merge this pull request.

**Review by erickzhao — CHANGES_REQUESTED** [review]
Thanks for the PR! I think this is an improvement over what we had before.

Could you actually paste in GitHub's stock Node gitignore instead? I think it'd be helpful:
https://github.com/github/gitignore/blob/master/Node.gitignore

**Comment by shauryaaher** [comment]
It's already present on https://github.com/github/blob/master/Node.gitignore.

**Comment by ckerr** [comment]
@shauryaaher I think @erickzhao means to copy the contents of https://github.com/github/gitignore/blob/master/Node.gitignore into https://github.com/shauryaaher/electron-quick-start/blob/master/.gitignore ?

**Comment by shauryaaher** [comment]
Fine. Got it.

**Pull request closed without merging**
