### PR TITLE
chore: Update electron to v4

### PR DESCRIPTION
**Pull request by master-atul**
updating the electron version to v4 in the starter

### CODE REVIEW

**Comment by jamzi** [comment]
Nice job, I was 6 minutes too late :) https://github.com/electron/electron-quick-start/pull/245

**Comment by jamzi** [comment]
Make sure to also include newly generate npm package-lock file.

**Comment by master-atul** [comment]
Oh yes @jamzi  Thanks for the input. Added package-lock update aswell

**Comment by shiftkey** [comment]
Superseded by #246 and #247 - thanks for noticing!

**Pull request closed without merging**
