### PR TITLE
use object destructuring

### PR DESCRIPTION
**Pull request by zeke**
This ES2015 syntax is a bit less verbose, and seems a nice pattern for hand-picking desired APIs from electron.

👀  @jlord @kevinsawicki

### CODE REVIEW

**Comment by jlord** [comment]
It would be my preference to treat this project like we do the demo app and [keep the ES6 to a minimum](https://github.com/electron/electron-api-demos/blob/master/CONTRIBUTING.md#code-style--es6) (that being `let`, `const` and string templates) since this aims to be an entry point to Electron for a broad group of people.

**Comment by zeke** [comment]
FWIW, this style is already in use throughout the electron documentation:

screen shot 2016-07-22 at 1 44 37 pm

**Comment by jlord** [comment]
@zeke yeah I know. I saw a pull request get merged and a bunch of stuff updated without a discussion. I would have said something then too if I'd made it in time :D

**Comment by zeke** [comment]
I see.. https://github.com/electron/electron/pull/5394

http://electron.atom.io/docs/api/synopsis/#destructuring-assignment

Given where we are today, with a proliferation of destructuring throughout the code and the docs of electron, are you open to introducing this concept in the demo app, too? That would unify the style of the electron codebase, the docs, the quickstart, and the demo app.

**Comment by zeke** [comment]
From an offline conversation with @jlord:

> I’d like to not discuss what is “cleaner” but rather what most people will recognize when they read it

For the purposes of this quickstart repo, familiarity trumps dexterity.

**Comment by Hum4n01d** [comment]
ah this is the same as the issue I just made #146 The current version doesn’t use destructuring though…

**Pull request closed without merging**
